// src/lib/city-slugs.ts

export const CITY_SLUG_ALIASES: Record<string, string> = {
  'essen': 'kfz-online-abmelden-essen',
  'heilbronn': 'auto-online-abmelden-heilbronn',
  'hagen-2': 'hagen',
  'worms-2': 'worms',
  'oestringen-2': 'oestringen',
  'berlin': 'berlin-zulassungsstelle',
  'landau-in-der-pfalz-2': 'landau-in-der-pfalz',
  'ehrenkirchen-2': 'ehrenkirchen',
  'wiesbaden-2': 'wiesbaden',
  'lueneburg-2': 'lueneburg',
  'paderborn-3': 'paderborn',
  'kassel-zulassungsstelle': 'kassel',
  'bonn-2': 'bonn',
  'ettlingen-2': 'ettlingen',
  'kyffhaeuserkreis-2': 'kyffhaeuserkreis',
  'kraichtal-2': 'kraichtal',
  'recklinghausen-2': 'recklinghausen',
  'kuenzelsau-2': 'auto-online-abmelden-in-kuenzelsau',
  'kuenzelsau-3': 'auto-online-abmelden-in-kuenzelsau',
  'auto-online-abmelden-muenchen-2': 'auto-online-abmelden-muenchen',
  'kfz-online-abmelden-hamburg': 'kfz-online-abmelden-in-hamburg',
  'kfz-abmelden-frankfurt-online': 'frankfurt',
  'kfz-zulassung-anhalt-bitterfeld': 'anhalt-bitterfeld',
  'kfz-zulassung-essen': 'kfz-online-abmelden-essen',
  'kfz-zulassung-leipzig': 'leipzig',
  'kfz-zulassung-remscheid': 'remscheid',
  'kfz-zulassung-wolfsburg': 'wolfsburg',
  'krefeld-strassenverkehrsamt': 'krefeld',
  'kuenzelsau': 'auto-online-abmelden-in-kuenzelsau',
  'laichingen': 'auto-online-abmelden-in-laichingen',
  'luebeck-zulassungsstelle': 'luebeck',
  'muenchen-zulassungsstelle': 'auto-online-abmelden-muenchen',
  'neuss': 'auto-online-abmelden-in-neuss',
  'stadtverkehrsamt-duisburg': 'duisburg',
  'zulassungsservice-aachen': 'aachen',
  'zulassungsservice-augsburg': 'augsburg',
  'zulassungsservice-bielefeld': 'bielefeld',
  'zulassungsservice-bochum': 'auto-online-abmelden-in-bochum',
  'zulassungsservice-bonn': 'bonn',
  'zulassungsservice-braunschweig': 'braunschweig',
  'zulassungsservice-chemnitz': 'chemnitz',
  'zulassungsservice-duesseldorf': 'duesseldorf',
  'zulassungsservice-freiburg': 'freiburg',
  'zulassungsservice-gelsenkirchen': 'auto-abmelden-online-in-gelsenkirchen',
  'zulassungsservice-karlsruhe': 'karlsruhe',
  'zulassungsservice-mainz': 'mainz',
  'zulassungsservice-mannheim': 'mannheim',
  'zulassungsservice-moenchengladbach': 'moenchengladbach',
  'zulassungsservice-muenster': 'muenster',
  'zulassungsservice-nuernberg': 'nuernberg',
  'zulassungsservice-oberhausen': 'oberhausen',
  'zulassungsservice-rostock': 'rostock',
  'zulassungsservice-wiesbaden': 'wiesbaden',
  'zulassungsservice-wuppertal': 'auto-online-abmelden-in-wuppertal',
  'zulassungsstelle-duesseldorf-termin': 'duesseldorf',
  'zulassungsstelle-laupheim': 'laupheim',
  'auto-abmelden-augsburg': 'augsburg',
  'auto-abmelden-bochum': 'auto-online-abmelden-in-bochum',
  'auto-abmelden-dortmund': 'kfz-online-abmelden-dortmund',
  'auto-abmelden-duesseldorf': 'duesseldorf',
  'auto-abmelden-duisburg': 'duisburg',
  'auto-abmelden-essen': 'kfz-online-abmelden-essen',
  'auto-abmelden-gelsenkirchen': 'auto-abmelden-online-in-gelsenkirchen',
  'auto-abmelden-nuernberg': 'nuernberg',
  'auto-abmelden-oberhausen': 'oberhausen',
  'auto-abmelden-stuttgart': 'zulassungsservice-stuttgart',
  'oberhausen-2': 'oberhausen',
  'paderborn-2': 'paderborn',
};

export const CITY_ENTRIES = [
  ['Aachen', 'aachen'],
  ['Ahrweiler', 'ahrweiler'],
  ['Aichtal', 'aichtal'],
  ['Alb-Donau-Kreis', 'alb-donau-kreis'],
  ['Altenkirchen', 'altenkirchen'],
  ['Altensteig', 'altensteig'],
  ['Altenburger Land', 'altenburger-land'],
  ['Alzey-Worms', 'alzey-worms'],
  ['Amberg', 'amberg'],
  ['Ammerland', 'ammerland'],
  ['Anhalt-Bitterfeld', 'anhalt-bitterfeld'],
  ['Ansbach', 'ansbach'],
  ['Aschaffenburg', 'aschaffenburg'],
  ['Augsburg', 'augsburg'],
  ['Aurich', 'aurich'],
  ['Bad Dürkheim', 'bad-duerkheim'],
  ['Bad Friedrichshall', 'bad-friedrichshall'],
  ['Bad Herrenalb', 'bad-herrenalb'],
  ['Bad Kreuznach', 'bad-kreuznach'],
  ['Bad Krozingen', 'bad-krozingen'],
  ['Bad Liebenzell', 'bad-liebenzell'],
  ['Bad Rappenau', 'bad-rappenau'],
  ['Bad Saulgau', 'bad-saulgau'],
  ['Bad Schönborn', 'bad-schoenborn'],
  ['Bad Waldsee', 'bad-waldsee'],
  ['Bad Wildbad Calmbach', 'bad-wildbad-calmbach'],
  ['Baden-Württemberg', 'baden-wurttemberg'],
  ['Baiersbronn', 'baisersbronn'],
  ['Bamberg', 'bamberg'],
  ['Barnim', 'barnim'],
  ['Berchtesgadener Land', 'berchtesgadener-land'],
  ['Berlin', 'berlin-zulassungsstelle'],
  ['Bernkastel-Wittlich', 'bernkastel-wittlich'],
  ['Besigheim', 'besigheim'],
  ['Biberach', 'biberach'],
  ['Bitburg-Prüm', 'bitburg-pruem'],
  ['Birkenfeld', 'birkenfeld'],
  ['Blaubeuren', 'blaubeuren'],
  ['Blaustein', 'blaustein'],
  ['Böblingen', 'boeblingen'],
  ['Bodenseekreis', 'bodenseekreis'],
  ['Bonn', 'bonn'],
  ['Borken', 'borken'],
  ['Bottrop', 'bottrop'],
  ['Brackenheim', 'brackenheim'],
  ['Braunschweig', 'braunschweig'],
  ['Breisach am Rhein', 'breisach-am-rhein'],
  ['Bretten', 'bretten'],
  ['Bühl', 'buehl'],
  ['Burgenlandkreis', 'burgenlandkreis'],
  ['Calw', 'calw'],
  ['Celle', 'celle'],
  ['Cham', 'cham'],
  ['Chemnitz', 'chemnitz'],
  ['Cloppenburg', 'cloppenburg'],
  ['Coburg', 'coburg'],
  ['Cochem-Zell', 'cochem-zell'],
  ['Coesfeld', 'coesfeld'],
  ['Cottbus', 'cottbus'],
  ['Crailsheim', 'crailsheim'],
  ['Cuxhaven', 'cuxhaven'],
  ['Dahme-Spreewald', 'dahme-spreewald'],
  ['Daun', 'daun'],
  ['Delmenhorst', 'delmenhorst'],
  ['Denzlingen', 'denzlingen'],
  ['Dessau-Roßlau', 'dessau-rosslau'],
  ['Diepholz', 'diepholz'],
  ['Donnersbergkreis', 'donnersbergkreis'],
  ['Donzdorf', 'donzdorf'],
  ['Dornstetten', 'dornstetten'],
  ['Düsseldorf', 'duesseldorf'],
  ['Duisburg', 'duisburg'],
  ['Ebersbach', 'ebersbach'],
  ['Echterdingen', 'echterdingen'],
  ['Efringen', 'efringen'],
  ['Eggenstein', 'eggenstein'],
  ['Ehingen', 'ehingen'],
  ['Ehrenkirchen', 'ehrenkirchen'],
  ['Eifelkreis Bitburg-Prüm', 'eifelkreis-bitburg-pruem'],
  ['Eisenach', 'eisenach'],
  ['Emmendingen', 'emmendingen'],
  ['Emden', 'emden'],
  ['Endingen am Kaiserstuhl', 'endingen-am-kaiserstuhl'],
  ['Ennepe-Ruhr-Kreis', 'ennepe-ruhr-kreis'],
  ['Enzkreis', 'enzkreis'],
  ['Eppingen', 'eppingen'],
  ['Erbach', 'erbach'],
  ['Erlangen', 'erlangen'],
  ['Eschwege-Witzenhausen', 'eschwege-witzenhausen'],
  ['Esslingen am Neckar', 'esslingen-am-neckar'],
  ['Ettlingen', 'ettlingen'],
  ['Euskirchen', 'euskirchen'],
  ['Flensburg', 'flensburg'],
  ['Filderstadt', 'filderstadt'],
  ['Frankenthal (Pfalz)', 'frankenthal-pfalz'],
  ['Frankfurt', 'frankfurt'],
  ['Freiburg', 'freiburg'],
  ['Freiburg Breisgau', 'freiburg-breisgau'],
  ['Frickenhausen', 'frickenhausen'],
  ['Friedrichshafen', 'friedrichshafen'],
  ['Fürth', 'fuerth'],
  ['Gaggenau', 'gaggenau'],
  ['Geislingen', 'geislingen'],
  ['Germersheim', 'germersheim'],
  ['Gerlingen', 'gerlingen'],
  ['Gerstetten', 'gerstetten'],
  ['Giengen an der Brenz', 'giengen-an-der-brenz'],
  ['Gifhorn', 'gifhorn'],
  ['Göppingen / Süßen', 'goeppingen-suessen'],
  ['Görlitz', 'goerlitz'],
  ['Goslar', 'goslar'],
  ['Gotha', 'gotha'],
  ['Graben-Neudorf', 'graben-neudorf'],
  ['Greiz', 'greiz'],
  ['Greifswald', 'greifswald'],
  ['Grenzach-Wyhlen', 'grenzach-wyhlen'],
  ['Großenhain', 'grossenhain'],
  ['Güstrow', 'guestrow'],
  ['Gütersloh', 'guetersloh'],
  ['Gundelfingen', 'gundelfingen'],
  ['Hagen', 'hagen'],
  ['Hameln-Pyrmont', 'hameln-pyrmont'],
  ['Hamburg', 'kfz-online-abmelden-in-hamburg'],
  ['Hamm', 'hamm'],
  ['Harburg', 'harburg'],
  ['Harz', 'harz'],
  ['Heidelberg', 'heidelberg'],
  ['Heidenheim / Herbrechtingen', 'heidenheim-herbrechtingen'],
  ['Heinsberg', 'heinsberg'],
  ['Helmstedt', 'helmstedt'],
  ['Herbolzheim', 'herbolzheim'],
  ['Herford', 'herford'],
  ['Herrenberg', 'herrenberg'],
  ['Hildburghausen', 'hildburghausen'],
  ['Hildesheim', 'hildesheim'],
  ['Hochsauerlandkreis', 'hochsauerlandkreis'],
  ['Höxter', 'hoexter'],
  ['Hohenlohekreis', 'hohenlohekreis'],
  ['Hof', 'hof'],
  ['Holzgerlingen', 'holzgerlingen'],
  ['Holzminden', 'holzminden'],
  ['Homburg', 'homburg'],
  ['Horb am Neckar', 'horb-am-neckar'],
  ['Ilsfeld', 'ilsfeld'],
  ['Ilm-Kreis', 'ilm-kreis'],
  ['Ingolstadt', 'ingolstadt'],
  ['Jena', 'jena'],
  ['Kaiserslautern', 'kaiserslautern'],
  ['Kandern', 'kandern'],
  ['Karlsruhe', 'karlsruhe'],
  ['Kassel', 'kassel'],
  ['Kelheim', 'kelheim'],
  ['Keltern', 'keltern'],
  ['Kaufbeuren', 'kaufbeuren'],
  ['Kempten', 'kempten'],
  ['Kenzingen', 'kenzingen'],
  ['Kirchen', 'kirchen'],
  ['Kirchheim', 'krichheim'],
  ['Kirchzarten', 'kirchzarten'],
  ['Kitzingen', 'kitzingen'],
  ['Kleve (Stadt)', 'kleve-stadt'],
  ['Koblenz', 'koblenz'],
  ['Kögen', 'koegen'],
  ['Köngen', 'koengen'],
  ['Königsbach-Stein', 'konigsbach-stein'],
  ['Konstanz', 'konstanz'],
  ['Kraichtal', 'kraichtal'],
  ['Krefeld', 'krefeld'],
  ['Kronach', 'kronach'],
  ['Künzelsau', 'auto-online-abmelden-in-kuenzelsau'],
  ['Kusel', 'kusel'],
  ['Kyffhäuserkreis', 'kyffhaeuserkreis'],
  ['Laichingen', 'auto-online-abmelden-in-laichingen'],
  ['Landau in der Pfalz', 'landau-in-der-pfalz'],
  ['Langenau', 'langenau'],
  ['Landkreis Aichach-Friedberg', 'landkreis-aichach-friedberg'],
  ['Landkreis Altötting', 'landkreis-altoetting'],
  ['Landkreis Amberg-Sulzbach', 'landkreis-amberg-sulzbach'],
  ['Landkreis Ansbach', 'landkreis-ansbach'],
  ['Landkreis Aschaffenburg', 'landkreis-aschaffenburg'],
  ['Landkreis Augsburg', 'landkreis-augsburg'],
  ['Landkreis Bad Kissingen', 'landkreis-bad-kissingen'],
  ['Landkreis Bad Tölz-Wolfratshausen', 'landkreis-bad-toelz-wolfratshausen'],
  ['Landkreis Biberach', 'landkreis-biberach'],
  ['Landkreis Böblingen', 'landkreis-boeblingen'],
  ['Landkreis Breisgau-Hochschwarzwald', 'landkreis-breisgau-hochschwarzwald'],
  ['Landkreis Calw', 'landkreis-calw'],
  ['Landkreis Emmendingen', 'landkreis-emmendingen'],
  ['Landkreis Esslingen', 'landkreis-esslingen'],
  ['Landkreis Freudenstadt', 'landkreis-freudenstadt'],
  ['Landkreis Göppingen', 'landkreis-goeppingen'],
  ['Landkreis Heidenheim', 'landkreis-heidenheim'],
  ['Landkreis Heilbronn', 'landkreis-heilbronn'],
  ['Landkreis Karlsruhe', 'landkreis-karlsruhe'],
  ['Landkreis Konstanz', 'landkreis-konstanz'],
  ['Landkreis Lörrach', 'landkreis-loerrach'],
  ['Landkreis Ludwigsburg', 'landkreis-ludwigsburg'],
  ['Landkreis Rastatt', 'landkreis-rastatt'],
  ['Landkreis Ravensburg', 'landkreis-ravensburg'],
  ['Landkreis Reutlingen', 'landkreis-reutlingen'],
  ['Landkreis Rottweil', 'landkreis-rottweil'],
  ['Landkreis Schwäbisch Hall', 'landkreis-schwaebisch-hall'],
  ['Landkreis Sigmaringen', 'landkreis-sigmaringen'],
  ['Landkreis Tübingen', 'landkreis-tuebingen'],
  ['Landkreis Tuttlingen', 'landkreis-tuttlingen'],
  ['Landkreis Waldshut', 'landkreis-waldshut'],
  ['Landkreise Rheinland-Pfalz', 'landkreise-in-rheinland-pfalz'],
  ['Laupheim', 'laupheim'],
  ['Lauffen', 'lauffen'],
  ['Lauffen Stadt', 'lauffen-stadt'],
  ['Leinfelden', 'leinfelden'],
  ['Leingarten', 'leingarten'],
  ['Leer', 'leer'],
  ['Leipzig', 'leipzig'],
  ['Leonberg', 'leonberg'],
  ['Leopoldshafen', 'leopoldshafen'],
  ['Leutkirch im Allgäu', 'leutkirch-im-allgaeu'],
  ['Leverkusen', 'leverkusen'],
  ['Linkenheim-Hochstetten', 'linkenheim-hochstetten'],
  ['Lippe', 'lippe'],
  ['Lörrach', 'loerrach'],
  ['Lübeck', 'luebeck'],
  ['Ludwigsburg', 'ludwigsburg'],
  ['Ludwigshafen am Rhein', 'ludwigshafen-am-rhein'],
  ['Ludwigslust-Parchim', 'ludwigslust-parchim'],
  ['Lüchow-Dannenberg', 'luechow-dannenberg'],
  ['Lüneburg', 'lueneburg'],
  ['Main-Tauber-Kreis', 'main-tauber-kreis'],
  ['Mainz', 'mainz'],
  ['Mainz-Bingen', 'mainz-bingen'],
  ['Malsch', 'malsch'],
  ['Mannheim', 'mannheim'],
  ['March', 'march'],
  ['Markdorf', 'markdorf'],
  ['Märkischer Kreis', 'maerkischer-kreis'],
  ['Mayen-Koblenz', 'mayen-koblenz'],
  ['Meckenbeuren', 'meckenbeuren'],
  ['Mecklenburgische Seenplatte', 'mecklenburgische-seenplatte'],
  ['Meißen', 'meissen'],
  ['Memmingen-Amendingen', 'memmingen-amendingen'],
  ['Merzig-Wadern', 'merzig-wadern'],
  ['Mettmann', 'mettmann'],
  ['Miesbach', 'miesbach'],
  ['Miltenberg', 'miltenberg'],
  ['Minden-Lübbecke', 'minden-luebbecke'],
  ['Mönchengladbach', 'moenchengladbach'],
  ['Mühlacker', 'muhlacker'],
  ['Mülheim an der Ruhr', 'muelheim-an-der-ruhr'],
  ['Müllheim', 'mullheim'],
  ['Münsingen', 'muensingen'],
  ['Münster', 'muenster'],
  ['Müritz', 'mueritz'],
  ['Nagold', 'nagold'],
  ['Neckar-Odenwald-Kreis', 'neckar-odenwald-kreis'],
  ['Neckarsulm', 'neckarsulm'],
  ['Neubrandenburg', 'neubrandenburg'],
  ['Neuenburg am Rhein', 'neuenburg-am-rhein'],
  ['Neuenstadt am Kocher', 'neuenstadt-am-kocher'],
  ['Neuhausen auf den Fildern / Nürtingen', 'neuhausen-auf-den-fildern-nuertingen'],
  ['Neuburg-Schrobenhausen', 'neuburg-schrobenhausen'],
  ['Neumarkt in der Oberpfalz', 'auto-online-abmelden-in-neumarkt-in-der-oberpfalz'],
  ['Neumünster', 'neumuenster'],
  ['Neustadt an der Weinstraße', 'neustadt-an-der-weinstrasse'],
  ['Neuwied', 'neuwied'],
  ['Niefern-Öschelbronn', 'niefern-oschelbronn'],
  ['Nordhausen', 'nordhausen'],
  ['Nordrhein-Westfalen', 'in-nordrhein-westfalen'],
  ['Nordsachsen', 'nordsachsen'],
  ['Nordwestmecklenburg', 'nordwestmecklenburg'],
  ['Northeim', 'northeim'],
  ['Nürnberg', 'nuernberg'],
  ['Oberallgäu', 'oberallgaeu'],
  ['Oberbergischer Kreis', 'oberbergischer-kreis'],
  ['Oberhavel', 'oberhavel'],
  ['Oberhausen', 'oberhausen'],
  ['Oberspreewald-Lausitz', 'oberspreewald-lausitz'],
  ['Obersulm', 'obersulm'],
  ['Ochsenhausen', 'ochsenhausen'],
  ['Öhringen', 'oehringen'],
  ['Östringen', 'oestringen'],
  ['Olpe', 'olpe'],
  ['Ortenaukreis', 'ortenaukreis'],
  ['Osnabrück', 'osnabrueck'],
  ['Ostalbkreis', 'ostalbkreis'],
  ['Osterholz', 'osterholz'],
  ['Ostfildern', 'ostfildern'],
  ['Ostprignitz-Ruppin', 'ostprignitz-ruppin'],
  ['Paderborn', 'paderborn'],
  ['Peine', 'peine'],
  ['Pforzheim', 'pforzheim'],
  ['Philippsburg', 'philippsburg'],
  ['Pinneberg', 'pinneberg'],
  ['Plön', 'ploen'],
  ['Plochingen / Weilheim an der Teck', 'plochingen-weilheim-an-der-teck'],
  ['Pfullendorf', 'auto-online-abmelden-pfullendorf'],
  ['Potsdam', 'potsdam'],
  ['Potsdam-Mittelmark', 'potsdam-mittelmark'],
  ['Prignitz', 'prignitz'],
  ['Quedlinburg', 'quedlinburg'],
  ['Rastatt', 'rastatt'],
  ['Recklinghausen', 'recklinghausen'],
  ['Regensburg', 'regensburg'],
  ['Remchingen', 'remchingen'],
  ['Remscheid', 'remscheid'],
  ['Rems-Murr-Kreis', 'rems-murr-kreis'],
  ['Renningen', 'renningen'],
  ['Reutlingen', 'reutlingen'],
  ['Rhein-Erft-Kreis', 'rhein-erft-kreis'],
  ['Rhein-Hunsrück-Kreis', 'rhein-hunsrueck-kreis'],
  ['Rhein-Lahn-Kreis', 'rhein-lahn-kreis'],
  ['Rhein-Neckar-Kreis', 'rhein-neckar-kreis'],
  ['Rhein-Pfalz-Kreis', 'rhein-pfalz-kreis'],
  ['Rhein-Sieg-Kreis', 'rhein-sieg-kreis'],
  ['Rheinfelden', 'rheinfelden'],
  ['Rheinstetten', 'rheinstetten'],
  ['Rhön-Grabfeld', 'rhoen-grabfeld'],
  ['Riedlingen', 'riedlingen'],
  ['Rosenheim', 'rosenheim'],
  ['Rostock', 'rostock'],
  ['Rotenburg (Wümme)', 'rotenburg-wuemme'],
  ['Rott weil', 'rott-weil'],
  ['Rottweil', 'rottweil'],
  ['Rutesheim', 'rutesheim'],
  ['Saalekreis', 'saalekreis'],
  ['Saalfeld-Rudolstadt', 'saalfeld-rudolstadt'],
  ['Saale-Holzland-Kreis', 'saale-holzland-kreis'],
  ['Saale-Orla-Kreis', 'saale-orla-kreis'],
  ['Salem', 'salem'],
  ['Salzlandkreis', 'salzlandkreis'],
  ['Sankt Wendel', 'sankt-wendel'],
  ['Schaumburg', 'schaumburg'],
  ['Schleswig-Flensburg', 'schleswig-flensburg'],
  ['Schopfheim', 'schopfheim'],
  ['Schömberg', 'schoemberg'],
  ['Schwaigern', 'schwaigern'],
  ['Schwalm-Eder-Kreis', 'schwalm-eder-kreis'],
  ['Schwandorf', 'schwandorf'],
  ['Schwäbisch Hall', 'schwaebisch-hall'],
  ['Schwarzwald-Baar-Kreis', 'schwarzwald-baar-kreis'],
  ['Schweinfurt', 'schweinfurt'],
  ['Segeberg', 'segeberg'],
  ['Siegen-Wittgenstein', 'siegen-wittgenstein'],
  ['Sigmaringen', 'sigmaringen'],
  ['Sindelfingen', 'sindelfingen'],
  ['Singen', 'singen'],
  ['Sömmerda', 'soemmerda'],
  ['Soest', 'soest'],
  ['Solingen', 'solingen'],
  ['Sonneberg', 'sonneberg'],
  ['Speyer', 'speyer'],
  ['Spree-Neiße', 'spree-neisse'],
  ['Stade', 'stade'],
  ['Starnberg', 'starnberg'],
  ['Steinfurt', 'steinfurt'],
  ['Steinen', 'steinen'],
  ['Stockach', 'stockach'],
  ['Stormarn', 'stormarn'],
  ['Straubenhardt', 'straubenhardt'],
  ['Straubing', 'straubing'],
  ['Straubing-Bogen', 'straubing-bogen'],
  ['Staufen im Breisgau', 'staufen-im-breisgau'],
  ['Stutensee', 'stutensee'],
  ['Suhl', 'suhl'],
  ['Teltow-Fläming', 'teltow-flaeming'],
  ['Teningen', 'teningen'],
  ['Tettnang', 'tettnang'],
  ['Tirschenreuth', 'tirschenreuth'],
  ['Titisee-Neustadt', 'titisee-neustadt'],
  ['Traunstein', 'traunstein'],
  ['Trier', 'trier'],
  ['Trier-Saarburg', 'trier-saarburg'],
  ['Tuttlingen', 'tuttlingen'],
  ['Uelzen', 'uelzen'],
  ['Uckermark', 'uckermark'],
  ['Ulm', 'ulm'],
  ['Unna', 'unna'],
  ['Überlingen', 'uberlingen'],
  ['Vaihingen an der Enz', 'vaihingen-an-der-enz'],
  ['Viersen', 'viersen'],
  ['Vogelsbergkreis', 'vogelsbergkreis'],
  ['Vogtlandkreis', 'vogtlandkreis'],
  ['Vorpommern-Greifswald', 'vorpommern-greifswald'],
  ['Vorpommern-Rügen', 'vorpommern-ruegen'],
  ['Waghäusel', 'waghaeusel'],
  ['Waldkirch', 'waldkirch'],
  ['Wangen im Allgäu', 'wangen-im-allgaeu'],
  ['Warendorf', 'warendorf'],
  ['Weiden in der Oberpfalz', 'weiden-in-der-oberpfalz'],
  ['Weil der Stadt', 'weil-der-stadt'],
  ['Weilheim am Rhein', 'weilheim-am-rhein'],
  ['Weimar', 'weimar'],
  ['Weimarer Land', 'weimarer-land'],
  ['Weinsberg', 'weinsberg'],
  ['Wendlingen', 'wendlingen'],
  ['Wernau', 'wernau'],
  ['Wesel', 'wesel'],
  ['Wesermarsch', 'wesermarsch'],
  ['Westerwaldkreis', 'westerwaldkreis'],
  ['Wiesbaden', 'wiesbaden'],
  ['Wildberg', 'wildberg'],
  ['Wilhelmshaven', 'wilhelmshaven'],
  ['Wittenberg', 'wittenberg'],
  ['Wittmund', 'wittmund'],
  ['Wolfenbüttel', 'wolfenbuettel'],
  ['Wolfsburg', 'wolfsburg'],
  ['Worms', 'worms'],
  ['Würzburg', 'wuerzburg'],
  ['Wunsiedel im Fichtelgebirge', 'wunsiedel-im-fichtelgebirge'],
  ['Zollernalbkreis', 'zollernalbkreis'],
  ['Zweibrücken', 'zweibruecken'],
  ['Zwickau', 'zwickau'],
  ['Auto online abmelden Bochum', 'auto-online-abmelden-in-bochum'],
  ['Auto online abmelden Heilbronn', 'auto-online-abmelden-heilbronn'],
  ['Auto online abmelden Karlsbad', 'auto-online-abmelden-karlsbad'],
  ['Auto online abmelden Köln', 'kfz-online-abmelden-koeln'],
  ['Auto online abmelden Landshut', 'auto-online-abmelden-landshut'],
  ['Auto online abmelden Neuss', 'auto-online-abmelden-in-neuss'],
  ['Auto online abmelden Wuppertal', 'auto-online-abmelden-in-wuppertal'],
  ['Baden-Baden', 'auto-online-abmelden-baden-baden'],
  ['Bremen', 'kfz-online-abmelden-bremen'],
  ['Dortmund', 'kfz-online-abmelden-dortmund'],
  ['KFZ-Zulassung Pirna', 'kfz-zulassung-pirna'],
  ['KFZ-Zulassungsstelle Göppingen', 'kfz-zulassungsstelle-goeppingen'],
  ['Zulassungsservice Erfurt', 'zulassungsservice-erfurt'],
  ['Zulassungsservice Halle (Saale)', 'zulassungsservice-halle-saale'],
  ['Zulassungsservice Hannover', 'zulassungsservice-hannover'],
  ['Zulassungsservice Kiel', 'zulassungsservice-kiel'],
  ['Zulassungsservice Magdeburg', 'zulassungsservice-magdeburg'],
  ['Zulassungsservice Stuttgart', 'zulassungsservice-stuttgart'],
  ['Dresden Kfz Zulassungsstelle', 'dresden-kfz-zulassungsstelle'],
  ['Essen', 'kfz-online-abmelden-essen'],
  ['München', 'auto-online-abmelden-muenchen'],
  ['Bielefeld', 'bielefeld'],
  ['Gelsenkirchen', 'auto-abmelden-online-in-gelsenkirchen'],
  ['Online KFZ Abmelden', 'online-kfz-abmelden'],
  ['Auto Online Abmelden Alle Seiten', 'auto-online-abmelden-alle-seiten'],

  // ── New city entries (batch 2026-04-15) ──
  ['Aalen', 'aalen'],
  ['Abensberg', 'abensberg'],
  ['Achern', 'achern'],
  ['Achim', 'achim'],
  ['Adorf', 'adorf'],
  ['Ahaus', 'ahaus'],
  ['Aichach', 'aichach'],
  ['Albstadt', 'albstadt'],
  ['Alfeld', 'alfeld'],
  ['Alsfeld', 'alsfeld'],
  ['Altena', 'altena'],
  ['Altenburg', 'altenburg'],
  ['Altenholz', 'altenholz'],
  ['Altötting', 'altoetting'],
  ['Alzenau', 'alzenau'],
  ['Alzey', 'alzey'],
  ['Andernach', 'andernach'],
  ['Anklam', 'anklam'],
  ['Annaberg-Buchholz', 'annaberg-buchholz'],
  ['Apolda', 'apolda'],
  ['Arnsberg', 'arnsberg'],
  ['Arnstadt', 'arnstadt'],
  ['Artern', 'artern'],
  ['Aschendorf', 'aschendorf'],
  ['Aschersleben', 'aschersleben'],
  ['Aue', 'aue'],
  ['Auerbach', 'auerbach'],
  ['Backnang', 'backnang'],
  ['Bad Aibling', 'bad-aibling'],
  ['Bad Arolsen', 'bad-arolsen'],
  ['Bad Bentheim', 'bad-bentheim'],
  ['Bad Bergzabern', 'bad-bergzabern'],
  ['Bad Berleburg', 'bad-berleburg'],
  ['Bad Brückenau', 'bad-brueckenau'],
  ['Bad Doberan', 'bad-doberan'],
  ['Bad Ems', 'bad-ems'],
  ['Bad Fallingbostel', 'bad-fallingbostel'],
  ['Bad Gandersheim', 'bad-gandersheim'],
  ['Bad Hersfeld', 'bad-hersfeld'],
  ['Bad Homburg vor der Höhe', 'bad-homburg-vor-der-hoehe'],
  ['Bad Kissingen', 'bad-kissingen'],
  ['Bad Königshofen', 'bad-koenigshofen'],
  ['Bad Kösen', 'bad-koesen'],
  ['Bad Kötzting', 'bad-koetzting'],
  ['Bad Langensalza', 'bad-langensalza'],
  ['Bad Liebenwerda', 'bad-liebenwerda'],
  ['Bad Mergentheim', 'bad-mergentheim'],
  ['Bad Münder', 'bad-muender'],
  ['Bad Neuenahr-Ahrweiler', 'bad-neuenahr-ahrweiler'],
  ['Bad Neustadt an der Saale', 'bad-neustadt-an-der-saale'],
  ['Bad Oeynhausen', 'bad-oeynhausen'],
  ['Bad Oldesloe', 'bad-oldesloe'],
  ['Bad Reichenhall', 'bad-reichenhall'],
  ['Bad Säckingen', 'bad-saeckingen'],
  ['Bad Salzuflen', 'bad-salzuflen'],
  ['Bad Salzungen', 'bad-salzungen'],
  ['Bad Schwalbach', 'bad-schwalbach'],
  ['Bad Segeberg', 'bad-segeberg'],
  ['Bad Tölz', 'bad-toelz'],
  ['Bad Wildungen', 'bad-wildungen'],
  ['Bad Windsheim', 'bad-windsheim'],
  ['Balingen', 'balingen'],
  ['Barntrup', 'barntrup'],
  ['Bautzen', 'bautzen'],
  ['Bayreuth', 'bayreuth'],
  ['Beckum', 'beckum'],
  ['Beelitz', 'beelitz'],
  ['Beeskow', 'beeskow'],
  ['Beilngries', 'beilngries'],
  ['Belzig', 'belzig'],
  ['Bergheim', 'bergheim'],
  ['Bergisch Gladbach', 'bergisch-gladbach'],
  ['Bergstraße', 'bergstrasse'],
  ['Bernburg', 'bernburg'],
  ['Bernkastel-Kues', 'bernkastel-kues'],
  ['Bersenbrück', 'bersenbrueck'],
  ['Biedenkopf', 'biedenkopf'],
  ['Bischofswerda', 'bischofswerda'],
  ['Bitburg', 'bitburg'],
  ['Bitterfeld', 'bitterfeld'],
  ['Blankenburg', 'blankenburg'],
  ['Bocholt', 'bocholt'],
  ['Bogen', 'bogen'],
  ['Boizenburg', 'boizenburg'],
  ['Bopfingen', 'bopfingen'],
  ['Boppard', 'boppard'],
  ['Borna', 'borna'],
  ['Brake', 'brake'],
  ['Bramsche', 'bramsche'],
  ['Brandenburg an der Havel', 'brandenburg-an-der-havel'],
  ['Bremerhaven', 'bremerhaven'],
  ['Bremervörde', 'bremervoerde'],
  ['Brilon', 'brilon'],
  ['Bruchsal', 'bruchsal'],
  ['Buchen', 'buchen'],
  ['Bückeburg', 'bueckeburg'],
  ['Büdingen', 'buedingen'],
  ['Burg', 'burg'],
  ['Burgdorf', 'burgdorf'],
  ['Burghausen', 'burghausen'],
  ['Burglengenfeld', 'burglengenfeld'],
  ['Buxtehude', 'buxtehude'],
  ['Calau', 'calau'],
  ['Castrop-Rauxel', 'castrop-rauxel'],
  ['Clausthal-Zellerfeld', 'clausthal-zellerfeld'],
  ['Cochem', 'cochem'],
  ['Dachau', 'dachau'],
  ['Darmstadt-Dieburg', 'darmstadt-dieburg'],
  ['Deggendorf', 'deggendorf'],
  ['Delitzsch', 'delitzsch'],
  ['Demmin', 'demmin'],
  ['Dessau', 'dessau'],
  ['Detmold', 'detmold'],
  ['Dieburg', 'dieburg'],
  ['Dietzenbach', 'dietzenbach'],
  ['Dillingen an der Donau', 'dillingen-an-der-donau'],
  ['Dingolfing', 'dingolfing'],
  ['Dinkelsbühl', 'dinkelsbuehl'],
  ['Dinslaken', 'dinslaken'],
  ['Dithmarschen', 'dithmarschen'],
  ['Döbeln', 'doebeln'],
  ['Donaueschingen', 'donaueschingen'],
  ['Donauwörth', 'donauwoerth'],
  ['Dormagen', 'dormagen'],
  ['Duderstadt', 'duderstadt'],
  ['Dülmen', 'duelmen'],
  ['Düren', 'dueren'],
  ['Ebersberg', 'ebersberg'],
  ['Eberswalde', 'eberswalde'],
  ['Ebern', 'ebern'],
  ['Ebermannstadt', 'ebermannstadt'],
  ['Eckernförde', 'eckernfoerde'],
  ['Eichsfeld', 'eichsfeld'],
  ['Eichstätt', 'eichstaett'],
  ['Eilenburg', 'eilenburg'],
  ['Einbeck', 'einbeck'],
  ['Eisenberg', 'eisenberg'],
  ['Eisenhüttenstadt', 'eisenhuettenstadt'],
  ['Eisleben', 'eisleben'],
  ['Elbe-Elster', 'elbe-elster'],
  ['Elmshorn', 'elmshorn'],
  ['Emsland', 'emsland'],
  ['Erding', 'erding'],
  ['Erkelenz', 'erkelenz'],
  ['Eschwege', 'eschwege'],
  ['Eutin', 'eutin'],
  ['Falkensee', 'falkensee'],
  ['Farchant', 'farchant'],
  ['Feuchtwangen', 'feuchtwangen'],
  ['Finsterwalde', 'finsterwalde'],
  ['Forchheim', 'forchheim'],
  ['Forst', 'forst'],
  ['Frankenberg', 'frankenberg'],
  ['Frankenthal', 'frankenthal'],
  ['Frankfurt am Main', 'frankfurt-am-main'],
  ['Frankfurt (Oder)', 'frankfurt-oder'],
  ['Freiberg', 'freiberg'],
  ['Freising', 'freising'],
  ['Freital', 'freital'],
  ['Freudenstadt', 'freudenstadt'],
  ['Freyung', 'freyung'],
  ['Friedberg', 'friedberg'],
  ['Friesland', 'friesland'],
  ['Fritzlar', 'fritzlar'],
  ['Fulda', 'fulda'],
  ['Fürstenau', 'fuerstenau'],
  ['Fürstenfeldbruck', 'fuerstenfeldbruck'],
  ['Fürstenwalde', 'fuerstenwalde'],
  ['Füssen', 'fuessen'],
  ['Gadebusch', 'gadebusch'],
  ['Gardelegen', 'gardelegen'],
  ['Garmisch-Partenkirchen', 'garmisch-partenkirchen'],
  ['Geislingen an der Steige', 'geislingen-an-der-steige'],
  ['Geithain', 'geithain'],
  ['Geldern', 'geldern'],
  ['Gera', 'gera'],
  ['Georgsmarienhütte', 'georgsmarienhuette'],
  ['Gerolstein', 'gerolstein'],
  ['Gersthofen', 'gersthofen'],
  ['Gießen', 'giessen'],
  ['Glauchau', 'glauchau'],
  ['Grafenau', 'grafenau'],
  ['Gräfenhainichen', 'graefenhainichen'],
  ['Gransee', 'gransee'],
  ['Grevenbroich', 'grevenbroich'],
  ['Grevesmühlen', 'grevesmuehlen'],
  ['Grimma', 'grimma'],
  ['Grimmen', 'grimmen'],
  ['Groß-Gerau', 'gross-gerau'],
  ['Grünstadt', 'gruenstadt'],
  ['Guben', 'guben'],
  ['Gummersbach', 'gummersbach'],
  ['Günzburg', 'guenzburg'],
  ['Gunzenhausen', 'gunzenhausen'],
  ['Hachenburg', 'hachenburg'],
  ['Hagenow', 'hagenow'],
  ['Halberstadt', 'halberstadt'],
  ['Haldensleben', 'haldensleben'],
  ['Hammelburg', 'hammelburg'],
  ['Hanau', 'hanau'],
  ['Hannoversch Münden', 'hannover-muenden'],
  ['Harsefeld', 'harsefeld'],
  ['Haßfurt', 'hassfurt'],
  ['Haßloch', 'hassloch'],
  ['Hauzenberg', 'hauzenberg'],
  ['Havelland', 'havelland'],
  ['Havelberg', 'havelberg'],
  ['Hechingen', 'hechingen'],
  ['Heidenheim', 'heidenheim'],
  ['Heilbad Heiligenstadt', 'heilbad-heiligenstadt'],
  ['Heppenheim', 'heppenheim'],
  ['Herborn', 'herborn-burg'],
  ['Hermeskeil', 'hermeskeil'],
  ['Hersbruck', 'hersbruck'],
  ['Herzberg', 'herzberg'],
  ['Höchstadt an der Aisch', 'hoechstadt-an-der-aisch'],
  ['Hofgeismar', 'hofgeismar'],
  ['Hofheim', 'hofheim'],
  ['Hohenlohe', 'hohenlohe'],
  ['Hohenmölsen', 'hohenmoelsen'],
  ['Hohenstein-Ernstthal', 'hohenstein-ernstthal'],
  ['Homberg', 'homberg'],
  ['Hückeswagen', 'hueckeswagen'],
  ['Hünfeld', 'huenfeld'],
  ['Hürth', 'huerth'],
  ['Husum', 'husum'],
  ['Idar-Oberstein', 'idar-oberstein'],
  ['Idstein', 'idstein'],
  ['Illertissen', 'illertissen'],
  ['Ilmenau', 'ilmenau'],
  ['Iserlohn', 'iserlohn'],
  ['Itzehoe', 'itzehoe'],
  ['Jessen', 'jessen'],
  ['Jever', 'jever'],
  ['Jünkerath', 'juenkerath'],
  ['Jülich', 'juelich'],
  ['Kamenz', 'kamenz'],
  ['Kandel', 'kandel'],
  ['Karben', 'karben'],
  ['Karlstadt', 'karlstadt'],
  ['Kehl', 'kehl'],
  ['Kemnath', 'kemnath'],
  ['Kempen', 'kempen'],
  ['Kirchheimbolanden', 'kirchheimbolanden'],
  ['Kirchhellen', 'kirchhellen'],
  ['Kirn', 'kirn'],
  ['Kleve', 'kleve'],
  ['Königs Wusterhausen', 'koenigs-wusterhausen'],
  ['Korbach', 'korbach'],
  ['Köthen', 'koethen'],
  ['Krumbach', 'krumbach'],
  ['Kulmbach', 'kulmbach'],
  ['Kyffhäuser', 'kyffhaeuser'],
  ['Kyritz', 'kyritz'],
  ['Lahn-Dill', 'lahn-dill'],
  ['Lahnstein', 'lahnstein'],
  ['Lahr', 'lahr'],
  ['Lambrecht', 'lambrecht'],
  ['Landau an der Isar', 'landau-an-der-isar'],
  ['Landsberg', 'landsberg'],
  ['Landstuhl', 'landstuhl'],
  ['Lauf', 'lauf'],
  ['Lauterbach', 'lauterbach'],
  ['Lemgo', 'lemgo'],
  ['Lennestadt', 'lennestadt'],
  ['Lenting', 'lenting'],
  ['Lichtenfels', 'lichtenfels'],
  ['Limburg', 'limburg'],
  ['Lindau', 'lindau'],
  ['Lingen', 'lingen'],
  ['Linsengericht', 'linsengericht'],
  ['Lippstadt', 'lippstadt'],
  ['Löbau', 'loebau'],
  ['Lohr', 'lohr'],
  ['Lübbecke', 'luebbecke'],
  ['Lübben', 'luebben'],
  ['Luckau', 'luckau'],
  ['Luckenwalde', 'luckenwalde'],
  ['Lüdenscheid', 'luedenscheid'],
  ['Lüdinghausen', 'luedinghausen'],
  ['Ludwigshafen', 'ludwigshafen'],
  ['Lünen', 'luenen'],
  ['Mainburg', 'mainburg'],
  ['Main-Spessart', 'main-spessart'],
  ['Main-Tauber', 'main-tauber'],
  ['Marburg', 'marburg'],
  ['Marienberg', 'marienberg'],
  ['Marktheidenfeld', 'marktheidenfeld'],
  ['Marktoberdorf', 'marktoberdorf'],
  ['Marl', 'marl'],
  ['Mayen', 'mayen'],
  ['Meckenheim', 'meckenheim'],
  ['Meiningen', 'meiningen'],
  ['Melle', 'melle'],
  ['Mellrichstadt', 'mellrichstadt'],
  ['Melsungen', 'melsungen'],
  ['Memmingen', 'memmingen'],
  ['Meppen', 'meppen'],
  ['Meerbusch', 'meerbusch'],
  ['Merseburg', 'merseburg'],
  ['Merzig', 'merzig'],
  ['Meschede', 'meschede'],
  ['Metzingen', 'metzingen'],
  ['Mindelheim', 'mindelheim'],
  ['Minden', 'minden'],
  ['Mittelsachsen', 'mittelsachsen'],
  ['Mittweida', 'mittweida'],
  ['Moers', 'moers'],
  ['Monschau', 'monschau'],
  ['Montabaur', 'montabaur'],
  ['Moosburg', 'moosburg'],
  ['Morbach', 'morbach'],
  ['Mühlacker', 'muehlacker'],
  ['Mühlhausen', 'muehlhausen'],
  ['Mühlheim am Main', 'muehlheim-am-main'],
  ['Mühldorf am Inn', 'muehldorf-am-inn'],
  ['Müllheim', 'muellheim'],
  ['Nabburg', 'nabburg'],
  ['Nauen', 'nauen'],
  ['Naumburg', 'naumburg'],
  ['Neresheim', 'neresheim'],
  ['Neuburg', 'neuburg'],
  ['Neuenbürg', 'neuenbuerg'],
  ['Neunkirchen', 'neunkirchen'],
  ['Neu-Ulm', 'neu-ulm'],
  ['Neuruppin', 'neuruppin'],
  ['Neustadt an der Aisch', 'neustadt-an-der-aisch'],
  ['Neustadt an der Waldnaab', 'neustadt-an-der-waldnaab'],
  ['Neustrelitz', 'neustrelitz'],
  ['Niebüll', 'nibuell'],
  ['Nienburg', 'nienburg'],
  ['Norden', 'norden'],
  ['Norderstedt', 'norderstedt'],
  ['Nördlingen', 'noerdlingen'],
  ['Oberviechtach', 'oberviechtach'],
  ['Ochsenfurt', 'ochsenfurt'],
  ['Oder-Spree', 'oder-spree'],
  ['Oldenburg', 'oldenburg'],
  ['Oppenheim', 'oppenheim'],
  ['Oranienburg', 'oranienburg'],
  ['Oschatz', 'oschatz'],
  ['Oschersleben', 'oschersleben'],
  ['Osterburg', 'osterburg'],
  ['Osterode am Harz', 'osterode-am-harz'],
  ['Ostholstein', 'ostholstein'],
  ['Ottweiler', 'ottweiler'],
  ['Parchim', 'parchim'],
  ['Parsberg', 'parsberg'],
  ['Pasewalk', 'pasewalk'],
  ['Passau', 'passau'],
  ['Perleberg', 'perleberg'],
  ['Pfaffenhofen', 'pfaffenhofen'],
  ['Pfarrkirchen', 'pfarrkirchen'],
  ['Pirmasens', 'pirmasens'],
  ['Pirna', 'pirna'],
  ['Plauen', 'plauen'],
  ['Pocking', 'pocking'],
  ['Pößneck', 'poessneck'],
  ['Prenzlau', 'prenzlau'],
  ['Prüm', 'pruem'],
  ['Pritzwalk', 'pritzwalk'],
  ['Querfurt', 'querfurt'],
  ['Rathenow', 'rathenow'],
  ['Ravensburg', 'ravensburg'],
  ['Regen', 'regen'],
  ['Rehau', 'rehau'],
  ['Rendsburg', 'rendsburg'],
  ['Rheda-Wiedenbrück', 'rheda-wiedenbrueck'],
  ['Rheine', 'rheine'],
  ['Ribnitz-Damgarten', 'ribnitz-damgarten'],
  ['Riesa', 'riesa'],
  ['Rietberg', 'rietberg'],
  ['Rinteln', 'rinteln'],
  ['Rockenhausen', 'rockenhausen'],
  ['Roding', 'roding'],
  ['Rotenburg an der Fulda', 'rotenburg-an-der-fulda'],
  ['Rotenburg an der Wümme', 'rotenburg-an-der-wuemme'],
  ['Rothenburg ob der Tauber', 'rothenburg-ob-der-tauber'],
  ['Roth', 'roth'],
  ['Rüdesheim', 'rudesheim'],
  ['Rüsselsheim', 'ruesselsheim'],
  ['Saarburg', 'saarburg'],
  ['Saarlouis', 'saarlouis'],
  ['Salzgitter', 'salzgitter'],
  ['Salzwedel', 'salzwedel'],
  ['Sangerhausen', 'sangerhausen'],
  ['Sankt Goar', 'sankt-goar'],
  ['Scheinfeld', 'scheinfeld'],
  ['Schleiden', 'schleiden'],
  ['Schleiz', 'schleiz'],
  ['Schleswig', 'schleswig'],
  ['Schlüchtern', 'schluechtern'],
  ['Schmalkalden', 'schmalkalden'],
  ['Schmölln', 'schmoelln'],
  ['Schongau', 'schongau'],
  ['Schorndorf', 'schorndorf'],
  ['Schrobenhausen', 'schrobenhausen'],
  ['Schwabach', 'schwabach'],
  ['Schwäbisch Gmünd', 'schwaebisch-gmuend'],
  ['Schwabmünchen', 'schwabmuenchen'],
  ['Schwalmstadt', 'schwalmstadt'],
  ['Schwelm', 'schwelm'],
  ['Schwerin', 'schwerin'],
  ['Sebnitz', 'sebnitz'],
  ['Selb', 'selb'],
  ['Seligenstadt', 'seligenstadt'],
  ['Senftenberg', 'senftenberg'],
  ['Siegburg', 'siegburg'],
  ['Siegen', 'siegen'],
  ['Simmern', 'simmern'],
  ['Soltau', 'soltau'],
  ['Sondershausen', 'sondershausen'],
  ['Sonthofen', 'sonthofen'],
  ['Stadthagen', 'stadthagen'],
  ['Steinburg', 'steinburg'],
  ['Stendal', 'stendal'],
  ['Stollberg', 'stollberg'],
  ['Stralsund', 'stralsund'],
  ['Strausberg', 'strausberg'],
  ['Sulzbach-Rosenberg', 'sulzbach-rosenberg'],
  ['Tauberbischofsheim', 'tauberbischofsheim'],
  ['Tecklenburg', 'tecklenburg'],
  ['Torgau', 'torgau'],
  ['Überlingen', 'ueberlingen'],
  ['Uffenheim', 'uffenheim'],
  ['Usingen', 'usingen'],
  ['Uslar', 'uslar'],
  ['Varel', 'varel'],
  ['Vechta', 'vechta'],
  ['Verden', 'verden'],
  ['Villingen-Schwenningen', 'villingen-schwenningen'],
  ['Vilsbiburg', 'vilsbiburg'],
  ['Vilshofen', 'vilshofen'],
  ['Vohenstrauß', 'vohenstrauss'],
  ['Völklingen', 'voelklingen'],
  ['Waiblingen', 'waiblingen'],
  ['Waldbröl', 'waldbroel'],
  ['Waldkraiburg', 'waldkraiburg'],
  ['Waldmünchen', 'waldmuenchen'],
  ['Waldshut-Tiengen', 'waldshut-tiengen'],
  ['Wangen', 'wangen'],
  ['Warburg', 'warburg'],
  ['Waren (Müritz)', 'waren-mueritz'],
  ['Wasserburg', 'wasserburg'],
  ['Weilburg', 'weilburg'],
  ['Weilheim', 'weilheim'],
  ['Weinheim', 'weinheim'],
  ['Weißenburg', 'weissenburg'],
  ['Weißenfels', 'weissenfels'],
  ['Weißwasser', 'weisswasser'],
  ['Werdau', 'werdau'],
  ['Wermelskirchen', 'wermelskirchen'],
  ['Wernigerode', 'wernigerode'],
  ['Wertheim', 'wertheim'],
  ['Westerburg', 'westerburg'],
  ['Westerstede', 'westerstede'],
  ['Wetzlar', 'wetzlar'],
  ['Wiesloch', 'wiesloch'],
  ['Wildeshausen', 'wildeshausen'],
  ['Winsen', 'winsen'],
  ['Wismar', 'wismar'],
  ['Witten', 'witten'],
  ['Wittlich', 'wittlich'],
  ['Witzenhausen', 'witzenhausen'],
  ['Wolfach', 'wolfach'],
  ['Wolfhagen', 'wolfhagen'],
  ['Wolfratshausen', 'wolfratshausen'],
  ['Wolgast', 'wolgast'],
  ['Wolmirstedt', 'wolmirstedt'],
  ['Worbis', 'worbis'],
  ['Wurzen', 'wurzen'],
  ['Wunsiedel', 'wunsiedel'],
  ['Zeitz', 'zeitz'],
  ['Zerbst', 'zerbst'],
  ['Zeven', 'zeven'],
  ['Zittau', 'zittau'],
  ['Zossen', 'zossen'],
] as const;

const RAW_SLUG_CITY_MAP: Record<string, string> = Object.fromEntries(
  CITY_ENTRIES.map(([name, slug]) => [slug, name])
);

export const ALIAS_SOURCE_SLUGS = new Set<string>(Object.keys(CITY_SLUG_ALIASES));
export const ALIAS_TARGET_SLUGS = new Set<string>(Object.values(CITY_SLUG_ALIASES));

function toTitleCaseFallback(input: string): string {
  return input
    .replace(/-/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map((word) => {
      if (!word) return word;
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join(' ');
}

function resolveFinalSlug(slug: string, maxDepth = 10): string {
  let current = slug;
  let depth = 0;
  const visited = new Set<string>();

  while (CITY_SLUG_ALIASES[current] && depth < maxDepth && !visited.has(current)) {
    visited.add(current);
    current = CITY_SLUG_ALIASES[current];
    depth++;
  }

  return current;
}

function resolveCityNameForSlug(slug: string): string {
  if (RAW_SLUG_CITY_MAP[slug]) {
    return sanitizeCityDisplayName(RAW_SLUG_CITY_MAP[slug]);
  }

  const resolved = resolveFinalSlug(slug);

  if (RAW_SLUG_CITY_MAP[resolved]) {
    return sanitizeCityDisplayName(RAW_SLUG_CITY_MAP[resolved]);
  }

  const reverseResolved = Object.entries(CITY_SLUG_ALIASES).find(
    ([, aliasTarget]) => aliasTarget === slug
  );

  if (reverseResolved) {
    const reverseSlug = reverseResolved[0];
    if (RAW_SLUG_CITY_MAP[reverseSlug]) {
      return sanitizeCityDisplayName(RAW_SLUG_CITY_MAP[reverseSlug]);
    }
  }

  return sanitizeCityDisplayName(toTitleCaseFallback(resolved));
}

function sanitizeCityDisplayName(name: string): string {
  const cleaned = name
    .replace(/^(?:auto|kfz)\s+online\s+abmelden(?:\s+in)?\s+/i, '')
    .replace(/^auto\s+abmelden\s+online(?:\s+in)?\s+/i, '')
    .replace(/^zulassungsservice\s+/i, '')
    .replace(/^kfz[-\s]?zulassungsstelle\s+/i, '')
    .replace(/\s+kfz[-\s]?zulassungsstelle$/i, '')
    .replace(/\s+zulassungsstelle$/i, '')
    .replace(/\s+/g, ' ')
    .trim();

  return cleaned || name.trim();
}

export const SLUG_CITY_MAP: Record<string, string> = (() => {
  const allSlugs = new Set<string>([
    ...CITY_ENTRIES.map(([, slug]) => slug),
    ...Object.keys(CITY_SLUG_ALIASES),
    ...Object.values(CITY_SLUG_ALIASES),
  ]);

  const finalMap: Record<string, string> = {};

  for (const slug of allSlugs) {
    finalMap[slug] = resolveCityNameForSlug(slug);
  }

  return finalMap;
})();

/**
 * Nur echte finale/live City-Slugs.
 * Keine Alias-Quellen hier rein.
 */
export const CITY_SLUGS = new Set<string>(
  Array.from(
    new Set(
      CITY_ENTRIES.map(([, slug]) => resolveFinalSlug(slug))
    )
  )
);

/**
 * Alle bekannten Slugs inkl. Aliase.
 * Nützlich für Redirect-/Auflösungslogik.
 */
export const ALL_CITY_SLUGS = new Set<string>([
  ...CITY_ENTRIES.map(([, slug]) => slug),
  ...Object.keys(CITY_SLUG_ALIASES),
  ...Object.values(CITY_SLUG_ALIASES),
]);

export function isCitySlug(slug?: string): boolean {
  if (!slug) return false;
  return CITY_SLUGS.has(resolveFinalSlug(slug));
}

export function isAliasCitySlug(slug?: string): boolean {
  if (!slug) return false;
  return ALIAS_SOURCE_SLUGS.has(slug);
}

export function getCityNameBySlug(slug?: string): string {
  if (!slug) return '';
  return SLUG_CITY_MAP[slug] || resolveCityNameForSlug(slug);
}

export function getResolvedCitySlug(slug?: string): string {
  if (!slug) return '';
  return resolveFinalSlug(slug);
}
