export const CITY_INTELLIGENCE_ENABLED = false;
export const CITY_DYNAMIC_GENERATORS_ENABLED = false;
export const CITY_SEMANTIC_DIVERSITY_ENABLED = false;
export const CITY_AUTHORITY_HUBS_ENABLED = false;

export const CITY_LIVE_PARITY_MODE =
  !CITY_INTELLIGENCE_ENABLED &&
  !CITY_DYNAMIC_GENERATORS_ENABLED &&
  !CITY_SEMANTIC_DIVERSITY_ENABLED;
